### ISSUE TITLE
Copied links paste twice

### ISSUE THREAD

**Issue by bashmakoff** [krzkaczor/hyperterm-paste#6] opened 2016-12-14 16:15 UTC
How to reproduce:
Copy any text from the link from web => paste into the terminal

Result:
Text concatenates twice. For example: **hyperterm-pastehyperterm-paste**

**Comment by bashmakoff** [comment] 2016-12-14 16:18
Can't reproduce anymore. It must have been a hyperterm issue

**Comment by krzkaczor** [comment] 2016-12-17 10:47
I have just experienced this issue. I bet that somehow Hyper API changed. I am on it...

**Comment by fgilio** [comment] 2016-12-19 16:06
I've just experienced this issue too. Anything I can help you with diagnosing?

**Comment by krzkaczor** [comment] 2016-12-19 16:08
@fgilio Since I restarted hyperterm I can't reproduce it :D I would suggest doing the same.

**Comment by fgilio** [comment] 2016-12-19 16:14
@krzkaczor well... same happened here. It's working ok :)

**Comment by pea** [comment] 2016-12-20 09:24
This problem happens to me with multiple panes/ split screens.

**Comment by fgilio** [comment] 2016-12-20 13:26
It's like @pea said
I recorded a video of it: https://www.dropbox.com/s/6pp49jowoqtpw93/hyperterm-paste_Copied_links_paste_twice.mp4?dl=0
Hope it helps

**Comment by krzkaczor** [comment] 2016-12-20 13:29
@pea @fgilio Thanks for detailed description guys! Now I can easily fix it. Stay tuned ;) I shall find some time tomorrow.

**Comment by xvalentino** [comment] 2017-01-09 21:14
Any leads on this. I'd be happy to give this a shot too.

**Comment by krzkaczor** [comment] 2017-01-09 23:03
@xvalentino I am sorry, I couldn't reproduce it and left it untouched. Honestly, I don't use `hyperterm` anymore (it's very unstable and I prefer iterm :( ).

**Comment by chrisdrackett** [comment] 2017-02-14 23:43
this happens for me when reloading the terminal. An extra paste per reload :)

**Comment by delcore92** [comment] 2017-03-30 02:41
I'm also experiencing this issue. It definitely seems to be related to panes opening and closing. Perhaps a variable is being shared across multiple pane instances? 
I'll do a bit of investigation and report back here 👍

**Comment by delcore92** [comment] 2017-03-31 00:43
I'm able to replicate it quite easily by refreshing the terminal (cmd + r).
If you output the `term.keyboard.handlers` at the beginning of the `onTerminal` function you will be able to see multiple `keydown` events. 

I'm starting to suspect that there is another plugin interacting with events and indirectly causing this behaviour. That is why some people are able to replicate the issue and others can't. 

Here are the plugins i have installed:

```
  plugins: [                                                            
    'hypercwd',                                                         
    'hyperterm-paste',                                                
    'hyperterm-alternatescroll',                                        
    'hyper-blink'
  ], 
```

**Comment by krzkaczor** [comment] 2017-10-02 20:26
I tested this today and can't reproduce. It looks like it could be fixed on hyperterm side. I am gonna close it for now. Reopen please if the issue still occurs.

**Closed by krzkaczor** 2017-10-02 20:26 UTC

**Comment by jrdnbwmn** [comment] 2017-12-28 22:23
I'm getting this again. It produces two copies instead of one of anything I paste (not just a link). Happens relatively consistently, but sometimes it doesn't happen. I can't figure out a pattern. 

When I remove hyperterm-paste, the problem stops.

**Comment by christiangenco** [comment] 2022-01-08 03:31
I'm getting this bug when typing keyboard expansions from [aText](https://trankynam.com/atext/):

https://user-images.githubusercontent.com/179361/148630128-982c9267-10ea-49d8-b25f-68c9663fb41f.mp4

**Comment by krzkaczor** [comment] 2022-01-08 15:41
@christiangenco fyi: this project is not maintaned anymore. Your best chance to fix this issue is to fork and fix it yourself.
